name: rss

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.1.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://kubernetes.io/feed.xml"
        characterLimit: "255"
        dry-run: "false"
        lastTime: "360h"
        labels: "k8s/blog"
