name: rss

on:
  workflow_dispatch:

jobs:
  k8s:
    runs-on: ubuntu-latest
    steps:
    - uses: guilhem/rss-issues-action@0.5.1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        feed: "https://kubernetes.io/feed.xml"
        dry-run: "false"
        characterLimit: "0"
        lastTime: "720h"
        labels: "k8s/blog"
